var tree = [["Lyrixx",,"",
                [["Lifestream","Lyrixx\/Lifestream.html","",
                [["Filter","Lyrixx\/Lifestream\/Filter.html","",
                [["FilterInterface","Lyrixx\/Lifestream\/Filter\/FilterInterface.html","",
                [        ]],["Twitter","Lyrixx\/Lifestream\/Filter\/Twitter.html","",
                [        ]]        ]],["Formatter","Lyrixx\/Lifestream\/Formatter.html","",
                [["FormatterInterface","Lyrixx\/Lifestream\/Formatter\/FormatterInterface.html","",
                [        ]],["Link","Lyrixx\/Lifestream\/Formatter\/Link.html","",
                [        ]]        ]],["Service","Lyrixx\/Lifestream\/Service.html","",
                [["AbstractFeed","Lyrixx\/Lifestream\/Service\/AbstractFeed.html"," < AbstractService",
                [        ]],["AbstractService","Lyrixx\/Lifestream\/Service\/AbstractService.html","",
                [        ]],["Atom","Lyrixx\/Lifestream\/Service\/Atom.html"," < AbstractFeed",
                [        ]],["FlickrAtom","Lyrixx\/Lifestream\/Service\/FlickrAtom.html"," < Atom",
                [        ]],["FlickrRss20","Lyrixx\/Lifestream\/Service\/FlickrRss20.html"," < Rss20",
                [        ]],["Github","Lyrixx\/Lifestream\/Service\/Github.html"," < Atom",
                [        ]],["Rss20","Lyrixx\/Lifestream\/Service\/Rss20.html"," < AbstractFeed",
                [        ]],["ServiceFeedInterface","Lyrixx\/Lifestream\/Service\/ServiceFeedInterface.html","",
                [        ]],["ServiceInterface","Lyrixx\/Lifestream\/Service\/ServiceInterface.html","",
                [        ]],["Twitter","Lyrixx\/Lifestream\/Service\/Twitter.html"," < Atom",
                [        ]]        ]],["Lifestream","Lyrixx\/Lifestream\/Lifestream.html","",
                [        ]],["Status","Lyrixx\/Lifestream\/Status.html","",
                [        ]],["StatusInterface","Lyrixx\/Lifestream\/StatusInterface.html","",
                [        ]],["Stream","Lyrixx\/Lifestream\/Stream.html","",
                [        ]],["StreamInterface","Lyrixx\/Lifestream\/StreamInterface.html","",
                [        ]]        ]]        ]]        ]

