var tree = [["Lyrixx",,"",
                [["Lifestream","Lyrixx\/Lifestream.html","",
                [["Filter","Lyrixx\/Lifestream\/Filter.html","",
                [["FilterInterface","Lyrixx\/Lifestream\/Filter\/FilterInterface.html","",
                [        ]],["TwitterMention","Lyrixx\/Lifestream\/Filter\/TwitterMention.html","",
                [        ]],["TwitterRetweet","Lyrixx\/Lifestream\/Filter\/TwitterRetweet.html","",
                [        ]]        ]],["Formatter","Lyrixx\/Lifestream\/Formatter.html","",
                [["FormatterInterface","Lyrixx\/Lifestream\/Formatter\/FormatterInterface.html","",
                [        ]],["Link","Lyrixx\/Lifestream\/Formatter\/Link.html","",
                [        ]],["TwitterHashtag","Lyrixx\/Lifestream\/Formatter\/TwitterHashtag.html","",
                [        ]],["TwitterMention","Lyrixx\/Lifestream\/Formatter\/TwitterMention.html","",
                [        ]]        ]],["Service","Lyrixx\/Lifestream\/Service.html","",
                [["AbstractService","Lyrixx\/Lifestream\/Service\/AbstractService.html","",
                [        ]],["Aggregate","Lyrixx\/Lifestream\/Service\/Aggregate.html","",
                [        ]],["Atom","Lyrixx\/Lifestream\/Service\/Atom.html"," < AbstractService",
                [        ]],["FlickrAtom","Lyrixx\/Lifestream\/Service\/FlickrAtom.html"," < Atom",
                [        ]],["FlickrRss20","Lyrixx\/Lifestream\/Service\/FlickrRss20.html"," < Rss20",
                [        ]],["Github","Lyrixx\/Lifestream\/Service\/Github.html"," < Atom",
                [        ]],["Rss20","Lyrixx\/Lifestream\/Service\/Rss20.html"," < AbstractService",
                [        ]],["ServiceInterface","Lyrixx\/Lifestream\/Service\/ServiceInterface.html","",
                [        ]],["Twitter","Lyrixx\/Lifestream\/Service\/Twitter.html"," < Atom",
                [        ]],["TwitterList","Lyrixx\/Lifestream\/Service\/TwitterList.html"," < AbstractService",
                [        ]],["TwitterSearch","Lyrixx\/Lifestream\/Service\/TwitterSearch.html"," < Atom",
                [        ]]        ]],["Status","Lyrixx\/Lifestream\/Status.html","",
                [["AdvancedStatus","Lyrixx\/Lifestream\/Status\/AdvancedStatus.html"," < Status",
                [        ]]        ]],["Lifestream","Lyrixx\/Lifestream\/Lifestream.html","",
                [        ]],["LifestreamFactory","Lyrixx\/Lifestream\/LifestreamFactory.html","",
                [        ]],["Status","Lyrixx\/Lifestream\/Status.html","",
                [        ]],["StatusInterface","Lyrixx\/Lifestream\/StatusInterface.html","",
                [        ]],["Stream","Lyrixx\/Lifestream\/Stream.html","",
                [        ]],["StreamInterface","Lyrixx\/Lifestream\/StreamInterface.html","",
                [        ]]        ]]        ]]        ]

