var tree = [["Lifestream","Lifestream.html","",
                [["Filter","Lifestream\/Filter.html","",
                [["FilterInterface","Lifestream\/Filter\/FilterInterface.html","",
                [        ]],["Twitter","Lifestream\/Filter\/Twitter.html","",
                [        ]]        ]],["Formatter","Lifestream\/Formatter.html","",
                [["FormatterInterface","Lifestream\/Formatter\/FormatterInterface.html","",
                [        ]],["Link","Lifestream\/Formatter\/Link.html","",
                [        ]]        ]],["Service","Lifestream\/Service.html","",
                [["AbstractFeed","Lifestream\/Service\/AbstractFeed.html"," < AbstractService",
                [        ]],["AbstractService","Lifestream\/Service\/AbstractService.html","",
                [        ]],["Atom","Lifestream\/Service\/Atom.html"," < AbstractFeed",
                [        ]],["FlickrAtom","Lifestream\/Service\/FlickrAtom.html"," < Atom",
                [        ]],["FlickrRss20","Lifestream\/Service\/FlickrRss20.html"," < Rss20",
                [        ]],["Github","Lifestream\/Service\/Github.html"," < Atom",
                [        ]],["Rss20","Lifestream\/Service\/Rss20.html"," < AbstractFeed",
                [        ]],["ServiceFeedInterface","Lifestream\/Service\/ServiceFeedInterface.html","",
                [        ]],["ServiceInterface","Lifestream\/Service\/ServiceInterface.html","",
                [        ]],["Twitter","Lifestream\/Service\/Twitter.html"," < Atom",
                [        ]]        ]],["Lifestream","Lifestream\/Lifestream.html","",
                [        ]],["Status","Lifestream\/Status.html","",
                [        ]],["StatusInterface","Lifestream\/StatusInterface.html","",
                [        ]],["Stream","Lifestream\/Stream.html","",
                [        ]],["StreamInterface","Lifestream\/StreamInterface.html","",
                [        ]]        ]]        ]

